auto-update: true
messages:
  spells:
    teleport_no_suitable_location: "No suitable place to teleport to"
stories:
  common:
    1:
      name: Quiet Days
      type: Elemental
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Present during the beginning of the world.
        - Everything was quiet and peaceful and serene.
    2:
      name: Everlasting
      type: Historical
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Having seen the rise and fall over empires
        - this block is proven everlasting and resolute.
    3:
      name: Toil
      type: Human
      shards: [ 0,0,0,0,1,0,1,0,1 ]
      lore:
        - Witness to the toil of poeple through the
        - ages, aiding where possible; a fruitless task.
    4:
      name: Good Life
      type: Philosophical
      shards: [ 0,0,0,0,1,0,0,0,2 ]
      lore:
        - Unknowing of the meaning of a good life, this
        - block has questions in questions remaining unanswered.
  uncommon:
    1:
      name: Quiet Days
      type: Elemental
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Present during the beginning of the world.
        - Everything was quiet and peaceful and serene.
    2:
      name: Everlasting
      type: Historical
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Having seen the rise and fall over empires
        - this block is proven everlasting and resolute.
  rare:
    1:
      name: Quiet Days
      type: Elemental
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Present during the beginning of the world.
        - Everything was quiet and peaceful and serene.
    2:
      name: Everlasting
      type: Historical
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Having seen the rise and fall over empires
        - this block is proven everlasting and resolute.
  epic:
    1:
      name: Quiet Days
      type: Elemental
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Present during the beginning of the world.
        - Everything was quiet and peaceful and serene.
    2:
      name: Everlasting
      type: Historical
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Having seen the rise and fall over empires
        - this block is proven everlasting and resolute.
  mythical:
    1:
      name: Quiet Days
      type: Elemental
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Present during the beginning of the world.
        - Everything was quiet and peaceful and serene.
    2:
      name: Everlasting
      type: Historical
      shards: [ 1,0,1,1,0,0,0,0,0 ]
      lore:
        - Having seen the rise and fall over empires
        - this block is proven everlasting and resolute.
  unique:
    1:
      name: Resolute
      type: Elemental
      shards: [ 2,0,1,1,0,0,0,0,0 ]
      lore:
        - Stone is the resolute backbone of the world's
        - makeup. Ever present and everlasting.
    2:
      name: Endless Potential
      type: Human
      shards: [ 0,1,0,0,2,0,1,0,1 ]
      lore:
        - This table magically creates items with a
        - minimal amount of materials. How it works
        - is still a mystery to this day.
      author: Ryhn12